{% set version = "1.3.1" %}
{% set sha256 = "e3b0c44298fc1c149afbf4c8996fb92427ae41e4649b934ca495991b7852b855" %}

package:
  name: qapa
  version: {{ version }}

source:
  url: https://github.com/morrislab/qapa/archive/refs/tags/v{{ version }}.tar.gz
  sha256: {{ sha256 }}

build:
  number: 0
  noarch: python
  entry_points:
    - qapa = qapa.qapa:main
  script: "{{ PYTHON }} -m pip install . --no-deps --ignore-installed -vv"

requirements:
  host:
    - python >= 3.8
    - pip
    - setuptools

  run:
    - python >= 3.8
    - six
    - pandas >= 0.24
    - numpy >= 1.10.0
    - biopython >= 1.76
    - pybedtools >= 0.7.9
    - r-base >= 3.4
    - r-dplyr >= 0.7
    - r-optparse
    - r-data.table
    - r-stringr
    - ucsc-gtftogenepred

test:
  imports:
    - qapa
  commands:
    - qapa --help

about:
  home: https://github.com/morrislab/qapa
  license: GPL-3.0
  summary: 'RNA-seq Quantification of Alternative Polyadenylation (QAPA)'

extra:
  identifiers:
    - biotools:qapa
    - doi:10.1186/s13059-018-1414-4
